import { contextBridge, ipcRenderer } from "electron";

const ALLOWED_CHANNELS: Record<string, boolean> = {
  "get-app-version": true,
  "storage:query": true,
  "storage:run": true,
  "storage:insert-product": true,
  "storage:get-products": true,
  "storage:save-features": true,
  "storage:export-all": true,
  "storage:cleanup": true,
  "storage:size": true,
  "comm:connect": true,
  "comm:disconnect": true,
  "comm:send": true,
  "sync:push-to-cloud": true,
  "collect:start": true,
  "collect:cancel": true,
  "collect:clear-queue": true,
  "collect:status": true,
  "collect:open-xhs-login": true,
  "collect:resume-queue": true,
  "collect:pause-queue": true,
  "collect:cookie-health": true,
  "collect:set-cookies": true,
  "collect:clear-cookies": true,
  "collect:get-cookies": true,
  "collect:enqueue-sharded": true,
  "collect:resume-checkpoint": true,
  "collect:clear-checkpoint": true,
  "collect:memory-usage": true,
  "collect:set-max-memory": true,
  "concurrency:get": true,
  "concurrency:set": true,
  "scheduler:start": true,
  "scheduler:stop": true,
  "scheduler:state": true,
  "scheduler:add-task": true,
  "scheduler:remove-task": true,
  "scheduler:toggle-task": true,
  "scheduler:update-frequency": true,
  "scheduler:get-tasks": true,
  "scheduler:timeline": true,
  "datamart:list-products": true,
  "datamart:get-product": true,
  "datamart:invalidate-cache": true,
  "products:list": true,
  "products:compare": true,
  "auth:login": true,
  "auth:register": true,
  "auth:logout": true,
  "permission:check": true,
  "permission:get-all": true,
  "permission:refresh": true,
  "app:minimize-to-tray": true,
  "app:get-platform": true,
  "playwright:start": true,
  "playwright:status": true,
  "playwright:cancel": true,
  "playwright:close": true,
  "license:activate": true,
  "license:get-current": true,
  "license:get-plan": true,
  "license:check-feature": true,
  "license:check-quota": true,
  "license:deactivate": true,
  "license:get-device-id": true,
  "license:is-expired": true,
  "sync:configure": true,
  "sync:start": true,
  "sync:stop": true,
  "sync:now": true,
  "sync:status": true,
  "sync:enqueue-product": true,
  "sync:enqueue-feature": true,
  "sync:ai-analyze": true,
  "sync:clear-pending": true,
  "sync:get-conflicts": true,
  "sync:get-all-conflicts": true,
  "sync:resolve-conflict": true,
  "sync:load-persisted-conflicts": true,
  "feature:compute": true,
  "feature:compute-all": true,
  "feature:get": true,
  "feature:stats": true,
  "notifications:get": true,
  "notifications:unread-count": true,
  "notifications:mark-read": true,
  "notifications:mark-all-read": true,
  "notifications:delete": true,
  "monitor:evaluate": true,
  "update:check": true,
  "update:download": true,
  "update:install": true,
  "update:status": true,
  "log:get-recent": true,
  "log:get-files": true,
  "log:export": true,
  "log:upload": true,
  "log:clear": true,
  "log:get-stats": true,
  "log:set-level": true,
  "log:set-upload-endpoint": true,
  "offline:status": true,
  "offline:pending-operations": true,
  "offline:clear-pending": true,
  "offline:check": true,
  "offline:enqueue": true,
  "window:open": true,
  "window:close": true,
  "window:list": true,
  "tray:update-status": true,
  "perf:latest": true,
  "perf:history": true,
  "perf:alerts": true,
  "perf:summary": true,
  "perf:clear": true,
};

const ALLOWED_LISTEN_CHANNELS: Record<string, boolean> = {
  "ws:connected": true,
  "ws:disconnected": true,
  "ws:message": true,
  "notification": true,
  "collect:result": true,
  "collect:risk_alert": true,
  "concurrency:changed": true,
  "resource:warning": true,
  "scheduler:task_executed": true,
  "sync:start": true,
  "sync:complete": true,
  "sync:error": true,
  "sync:pulled": true,
  "sync:conflict:detected": true,
  "sync:conflict:resolved": true,
  "ai:result": true,
  "notification:local": true,
  "risk:detected": true,
  "risk:critical": true,
  "queue:paused": true,
  "queue:resumed": true,
  "update:download-progress": true,
  "update:downloaded": true,
};

contextBridge.exposeInMainWorld("electronAPI", {
  invoke: (channel: string, ...args: unknown[]) => {
    if (!ALLOWED_CHANNELS[channel]) {
      throw new Error(`IPC channel "${channel}" is not allowed`);
    }
    return ipcRenderer.invoke(channel, ...args);
  },
  on: (channel: string, callback: (...args: unknown[]) => void) => {
    if (!ALLOWED_LISTEN_CHANNELS[channel]) {
      throw new Error(`IPC listen channel "${channel}" is not allowed`);
    }
    const subscription = (_event: Electron.IpcRendererEvent, ...args: unknown[]) => callback(...args);
    ipcRenderer.on(channel, subscription);
    return () => ipcRenderer.removeListener(channel, subscription);
  },
  getAppVersion: () => ipcRenderer.invoke("get-app-version"),
  getPlatform: () => process.platform,
});
