version: 0.1.0
files:
  - url: XHS365-Setup-0.1.0.exe
    sha512: 9xeX/DHU+J0OrdkUDBbLVHe45pMJkj9PmKFHkpECM9uhBTkip+fbTBHVvXK6XFGYZY+6hUDlLoO3m4Ce26CnVA==
    size: 106345952
path: XHS365-Setup-0.1.0.exe
sha512: 9xeX/DHU+J0OrdkUDBbLVHe45pMJkj9PmKFHkpECM9uhBTkip+fbTBHVvXK6XFGYZY+6hUDlLoO3m4Ce26CnVA==
releaseDate: '2026-05-17T10:21:24.508Z'
