version: 0.1.0
files:
  - url: XHS365-Setup-0.1.0.exe
    sha512: PlK4TXab6DI54MWVaB5qnWIyvzxL8LJSRIWExPYBqMHDMTaS7p++9iAe2mB/yd6Ln9CAwWb1nmII1ngwngivXQ==
    size: 78341010
path: XHS365-Setup-0.1.0.exe
sha512: PlK4TXab6DI54MWVaB5qnWIyvzxL8LJSRIWExPYBqMHDMTaS7p++9iAe2mB/yd6Ln9CAwWb1nmII1ngwngivXQ==
releaseDate: '2026-05-12T11:25:32.353Z'
