from typing import Literal

PlanTier = Literal["free", "pro", "premium", "enterprise"]

PLAN_HIERARCHY: dict[PlanTier, int] = {
    "free": 0,
    "pro": 1,
    "premium": 2,
    "enterprise": 3,
}


def is_plan_sufficient(user_plan: PlanTier, required_plan: PlanTier) -> bool:
    return PLAN_HIERARCHY.get(user_plan, 0) >= PLAN_HIERARCHY.get(required_plan, 0)


PLAN_LIMITS: dict[PlanTier, dict] = {
    "free": {
        "maxProducts": 3,
        "maxConcurrency": 1,
        "dailyCollectLimit": 20,
        "maxScheduleTasks": 0,
        "aiCallsPerDay": 3,
        "discoverySearchPerDay": 5,
        "discoveryBurstPerDay": 0,
        "excelImportPerDay": 0,
        "historyDays": 7,
        "anomalyDetection": False,
        "aipicDailyLimit": 3,
        "aipicMaxQuality": "standard",
    },
    "pro": {
        "maxProducts": 50,
        "maxConcurrency": 5,
        "dailyCollectLimit": 500,
        "maxScheduleTasks": 20,
        "aiCallsPerDay": 50,
        "discoverySearchPerDay": 50,
        "discoveryBurstPerDay": 0,
        "excelImportPerDay": 10,
        "historyDays": 30,
        "anomalyDetection": False,
        "aipicDailyLimit": 50,
        "aipicMaxQuality": "hd",
    },
    "premium": {
        "maxProducts": 500,
        "maxConcurrency": 8,
        "dailyCollectLimit": 2000,
        "maxScheduleTasks": 100,
        "aiCallsPerDay": 200,
        "discoverySearchPerDay": 200,
        "discoveryBurstPerDay": 50,
        "excelImportPerDay": 50,
        "historyDays": 90,
        "anomalyDetection": True,
        "aipicDailyLimit": 200,
        "aipicMaxQuality": "ultra",
    },
    "enterprise": {
        "maxProducts": -1,
        "maxConcurrency": 10,
        "dailyCollectLimit": -1,
        "maxScheduleTasks": -1,
        "aiCallsPerDay": -1,
        "discoverySearchPerDay": -1,
        "discoveryBurstPerDay": -1,
        "excelImportPerDay": -1,
        "historyDays": -1,
        "anomalyDetection": True,
        "aipicDailyLimit": -1,
        "aipicMaxQuality": "ultra",
    },
}

PLAN_FEATURES_MAP: dict[str, list[str]] = {
    "free": [
        "gate:monitor:add",
        "gate:monitor:manual_refresh",
        "gate:monitor:waterfall",
        "gate:collect:create",
        "gate:ai:basic_analysis",
        "gate:discovery:search",
        "gate:aipic:generate",
    ],
    "pro": [
        "gate:monitor:add",
        "gate:monitor:manual_refresh",
        "gate:monitor:auto_refresh",
        "gate:monitor:history",
        "gate:monitor:export",
        "gate:monitor:waterfall",
        "gate:monitor:category",
        "gate:monitor:growth_24h",
        "gate:monitor:compare",
        "gate:collect:create",
        "gate:import:excel",
        "gate:ai:basic_analysis",
        "gate:ai:trend_score",
        "gate:ai:report",
        "gate:collect:playwright",
        "gate:collect:author_full",
        "gate:sync:cloud",
        "gate:discovery:search",
        "gate:aipic:generate",
        "gate:aipic:hd",
        "gate:aipic:style",
    ],
    "premium": [
        "gate:monitor:add",
        "gate:monitor:manual_refresh",
        "gate:monitor:auto_refresh",
        "gate:monitor:history",
        "gate:monitor:export",
        "gate:monitor:waterfall",
        "gate:monitor:category",
        "gate:monitor:growth_24h",
        "gate:monitor:anomaly",
        "gate:monitor:compare",
        "gate:collect:create",
        "gate:import:excel",
        "gate:ai:basic_analysis",
        "gate:ai:trend_score",
        "gate:ai:prediction",
        "gate:ai:risk_warning",
        "gate:ai:report",
        "gate:ai:batch_analysis",
        "gate:collect:playwright",
        "gate:collect:author_full",
        "gate:sync:cloud",
        "gate:discovery:search",
        "gate:discovery:burst",
        "gate:aipic:generate",
        "gate:aipic:hd",
        "gate:aipic:ultra",
        "gate:aipic:style",
        "gate:aipic:batch",
        "gate:aipic:api",
    ],
    "enterprise": [
        "gate:monitor:add",
        "gate:monitor:manual_refresh",
        "gate:monitor:auto_refresh",
        "gate:monitor:history",
        "gate:monitor:export",
        "gate:monitor:waterfall",
        "gate:monitor:category",
        "gate:monitor:growth_24h",
        "gate:monitor:anomaly",
        "gate:monitor:compare",
        "gate:collect:create",
        "gate:import:excel",
        "gate:ai:basic_analysis",
        "gate:ai:trend_score",
        "gate:ai:prediction",
        "gate:ai:risk_warning",
        "gate:ai:report",
        "gate:ai:batch_analysis",
        "gate:collect:playwright",
        "gate:collect:author_full",
        "gate:sync:cloud",
        "gate:discovery:search",
        "gate:discovery:burst",
        "gate:aipic:generate",
        "gate:aipic:hd",
        "gate:aipic:ultra",
        "gate:aipic:style",
        "gate:aipic:batch",
        "gate:aipic:api",
    ],
}
